resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/a136c4242b9c9f6124b811329bc8ccdfd86c514e/snapshot.yaml

packages:
- shelley/chain-and-ledger/executable-spec
- byron/chain/executable-spec
- byron/ledger/executable-spec
- byron/semantics/executable-spec
- shelley/chain-and-ledger/dependencies/non-integer

extra-deps:
- sequence-0.9.8
- tasty-hedgehog-1.0.0.1 # Needed due to https://github.com/qfpl/tasty-hedgehog/issues/30
- Unique-0.4.7.6
- bimap-0.4.0
- moo-1.2
- gray-code-0.3.1
- typerep-map-0.3.1
- git: https://github.com/input-output-hk/goblins
  commit: ba4d76f8d27bcd436fd26f8c4085e89d82d3d2d5

nix:
  shell-file: nix/stack-shell.nix
