resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/b25eed0ab3b6da51bc10970759d491331e56c822/snapshot.yaml

packages:
- shelley/chain-and-ledger/executable-spec
- byron/chain/executable-spec
- byron/ledger/executable-spec
- byron/semantics/executable-spec
- shelley/chain-and-ledger/dependencies/non-integer

extra-deps:
- capability-0.2.0.0
- moo-1.2
- gray-code-0.3.1
- sequence-0.9.8
- tasty-hedgehog-0.2.0.0
- tasty-hedgehog-coverage-0.1.0.0
- git: https://github.com/input-output-hk/goblins
  commit: 972f80d603e5f988e16fa4b9a9645dbfc4edd654
